autenticacion:
    resource: "@AutenticacionBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"    
    
comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /    
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 