autenticacion:
    resource: "@AutenticacionBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /
    
comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /    