<?php

namespace BackendBundle\Repository;

/**
 * Datos_UniformesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Datos_UniformesRepository extends \Doctrine\ORM\EntityRepository
{
}
