<?php

namespace BackendBundle\Repository;

/**
 * Datos_MedicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Datos_MedicosRepository extends \Doctrine\ORM\EntityRepository
{
}
