<?php

namespace BackendBundle\Repository;

/**
 * Datos_LaboralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Datos_LaboralesRepository extends \Doctrine\ORM\EntityRepository
{
}
